import './globals.css'
import { Inter } from 'next/font/google'
import {ClerkProvider} from '@clerk/nextjs'
import { dark } from '@clerk/themes';
import { ptBR } from "@clerk/localizations";

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

export const metadata = {
  title: 'To-do app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider localization={ptBR} appearance={{
      baseTheme: dark,
      elements: {
        formFieldInput: "bg-zinc-900 rounded focus:outline-none focus:ring-1 focus:ring-teal-600",
        formButtonPrimary: "bg-teal-600 hover:bg-teal-700 transition-colors",
        footerActionLink: 'text-teal-600 hover:text-teal-600',
        card: "bg-zinc-900"
      }
    }}>
      <html lang="en">
        <body className={`${inter.variable} font-inter`}>{children}</body>
      </html>
    </ClerkProvider>
  )
}
